project_name: "tfversion"

# before are hooks that will be run before any builds are done, so good to put install scripts and stuff that your builds need here
before:
  hooks:
    # Remove unused packaged from the build process
    - go mod tidy
    - go generate

builds:
  - main: ./main.go
    binary: tfversion
    goos: ["linux", "darwin", "windows"]
    goarch: ["386", "amd64", "arm64"]
    ldflags:
      - -s -w -X "github.com/tfversion/tfversion/cmd.version={{.Version}}"
    env:
      - CGO_ENABLED=0

changelog:
  sort: "asc"
  filters:
    exclude: ["^docs:", "demo", "^hugo:", "Merge pull request", "Merge branch"]

brews:
  - tap:
      owner: tfversion
      name: homebrew-tfversion
    name: tfversion
    homepage: "https://github.com/tfversion/tfversion"
    description: "A simple tool to manage Terraform versions"
    license: "MIT"
    skip_upload: auto
    commit_author:
      name: Bruno Schaatsbergen
      email: git@tfversion.com
    folder: Formula
    install: |-
      bin.install "tfversion"
    test: |
      system "#{bin}/tfversion -v"
